### ISSUE TITLE
Link warning

### ISSUE THREAD

**Issue by nelson2005** [kobalicek/mathpresso-ng#2]
I'm not sure if you've seen this, but I'm embedding mathpresso-ng and asmjit, get a linker warning

1>LINK : warning C4744: 'struct asmjit::X86RegData const asmjit::x86RegData' has different type in 'C:\work\sim\common\asmjit\src\x86operand_regs.cpp' and 'C:\work\sim\common\asmjit\src\mathpresso_jit.cpp': 'union (3152 bytes)' and 'struct (3152 bytes)'

I'm using Visual Studio 2013 on Windows 7, if that's useful.

**Comment by kobalicek** [comment]
This warning is unfortunately unavoidable at the moment.

It's harmless. Asmjit uses a nasty trick to make sure the `X86RegData` struct is `static const` and put in read-only section, instead of initializing it at the application's startup.

**Comment by nelson2005** [comment]
Okay, no worries.  Since the sizes were the same, I guessed that it was okay.
